import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

//Font style downloaded locally
const oswald = localFont({
  src: "./fonts/Oswald/Oswald-VariableFont_wght.ttf",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.className} antialiased`}>{children}</body>
    </html>
  );
}
